variables:
  service_name: bars-mock-receiver-proxy
  short_service_name: bmr
  service_base_path: bars-mock-receiver-proxy
  product_display_name: Bars Mock Receiver
  product_description: This proxy only acts as a mock receiver.
  spec_file: bars-mock-receiver-proxy.json